version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crm_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oleg_crm
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: .
    container_name: crm_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  ml:
    build:
      context: ./backend
      dockerfile: ml_service/Dockerfile.ml
    container_name: crm_ml
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./backend/ml_service/models:/app/ml_service/models
      - ./backend/models:/app/models

volumes:
  postgres_data:
